export const FLICKR_BASE_URL = 'https://api.flickr.com/services/feeds/photos_public.gne';

export const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY';
export const CLEAR_SEARCH_QUERY = 'CLEAR_SEARCH_QUERY';

export const FLICKR_API_REQUEST = 'FLICKR_API_REQUEST';
export const FLICKR_API_SUCCESS = 'FLICKR_API_SUCCESS';
export const FLICKR_API_FAILURE = 'FLICKR_API_FAILURE';

export const SOUNDCLOUD_API_REQUEST = 'SOUNDCLOUD_API_REQUEST';
export const SOUNDCLOUD_API_SUCCESS = 'SOUNDCLOUD_API_SUCCESS';
export const SOUNDCLOUD_API_FAILURE = 'SOUNDCLOUD_API_FAILURE';
